Add controllers
NurievLinar/java-shareit pull request #1
Opened 2023-04-07 21:54 UTC by NurievLinar

2023-04-09 04:38 UTC, sergeymamonov requested changes

2023-04-09 04:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        for (Item item1 : itemList) {
item1 и item - не очень понятно, какая разница между этими переменными. Нужно использовать слова, чтобы было понятнее. Например, currentItem и так далее.

2023-04-09 04:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                if (item.getAvailable().equals(true) && (item.getName().toLowerCase().contains(substring) ||
item.getAvailable().equals(true) - можно проще item.getAvailable()

2023-04-09 04:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends Exception {
А почему не сделали наследование от RuntimeException? Тогда не нужно будет указывать во всех методах throws DuplicateEmailException

2023-04-09 19:59 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        for (Item item1 : itemList) {
Исправил.

2023-04-09 19:59 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                if (item.getAvailable().equals(true) && (item.getName().toLowerCase().contains(substring) ||
Исправил.

2023-04-09 19:59 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/user/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends Exception {
Исправил. Спасибо.

2023-04-10 19:49 UTC, sergeymamonov approved these changes

2023-05-12 22:07 UTC, merged