Add bookings
NurievLinar/java-shareit pull request #2
Opened 2023-05-12 22:00 UTC by NurievLinar

2023-05-14 21:16 UTC, sergeymamonov requested changes

2023-05-14 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(BookingService bookingService) {
Не обязательно писать конструктор руками, если можно воспользоваться аннотацией Lombok @AllArgsConstructor? Аналогично и для других классов, где можно воспользоваться этой аннотацией

2023-05-14 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        }
Лучше всегда делать ветку default на случай, если мы получим статус, который нам неизвестен, чтобы можно было кинуть ошибку или что-то еще сделать в такой ситуации.

Ниже аналогично.

2023-05-14 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<Comment> commentList = commentRepository.findAllByItem_Id(itemDto.getId());
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-05-14 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Optional<Booking> lastBooking = bookingRepository.findTop1BookingByItem_IdAndEndIsBeforeAndStatusIs(
Здесь и в строке 120 аналогично, запросы к БД в цикле.

2023-05-14 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Это исключение где-то используется?

2023-05-14 21:16 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    name  VARCHAR NOT NULL,
В скриптах sql размер varchar должен быть ограничен.

2023-05-16 17:12 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(BookingService bookingService) {
Исправлено

2023-05-16 17:14 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/user/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Исправлено

2023-05-17 19:02 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        }
Исправлено.

2023-05-20 14:12 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Optional<Booking> lastBooking = bookingRepository.findTop1BookingByItem_IdAndEndIsBeforeAndStatusIs(
Исправлено.

2023-05-20 14:12 UTC, NurievLinar commented on src/main/resources/schema.sql
> +    name  VARCHAR NOT NULL,
Исправлено.

2023-05-20 14:18 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<Comment> commentList = commentRepository.findAllByItem_Id(itemDto.getId());
Исправлено.

2023-05-21 21:06 UTC, sergeymamonov approved these changes

2023-05-23 17:04 UTC, merged