ТЗ 15. ItemRequest.
NurievLinar/java-shareit pull request #3
Opened 2023-05-25 08:53 UTC by NurievLinar

2023-05-26 04:27 UTC, sergeymamonov requested changes
ErrorHandler - лучше сделать обработку ошибок времени выполнения, а так же на 404 статус.

Проверьте по коду, названия для метода get слишком общее, нужно добавить конкретики.

2023-05-26 04:27 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          if (booking.getStatus().equals(Status.APPROVED) ||
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE.

То есть Status.APPROVED.equals(...).

Это необходимо поправить во всех места в проекте.

2023-05-26 04:27 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>                  break;
Лучше информировать пользователя в таком случае (например кинуть ошибку, залогировать). То есть мы получили неподдерживаемый статус и не сообщили об этом пользователю

2023-05-26 04:27 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (from < 0) throw new PaginationException("Ошибка пагинации");
Проверка пагинации выполняется в коде несколько раз. Тогда лучше вынести в отдельный метод, класс и не будет дублирования кода.

2023-05-26 04:27 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
В 156 строке метод comment. Названия методов должны начинаться с глагола.

2023-05-26 04:27 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public List<ItemRequestDto> get(@RequestHeader("X-Sharer-User-Id") Long userId) {
Лучше переименовать методы, сейчас из get понятно что этот метод вернет, какой-то результат, но не понятно какой.

2023-05-26 04:27 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    public List<ItemRequestDto> get(Long userId) {
Добавить конкретики в название.

2023-05-26 17:24 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          if (booking.getStatus().equals(Status.APPROVED) ||
Исправлено.

2023-05-26 17:26 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>                  break;
Исправлено.

2023-05-26 18:59 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (from < 0) throw new PaginationException("Ошибка пагинации");
Исправлено.

2023-05-26 19:08 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
Исправлено.

2023-05-26 19:15 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public List<ItemRequestDto> get(@RequestHeader("X-Sharer-User-Id") Long userId) {
Исправлено.

2023-05-26 19:15 UTC, NurievLinar commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    public List<ItemRequestDto> get(Long userId) {
Исправлено.

2023-05-27 12:01 UTC, sergeymamonov approved these changes

2023-05-27 12:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        validatePagination(from, size);
В данном случае validatePagination избыточно, так как в методе of проверяются входные параметры.

2023-05-27 12:01 UTC, sergeymamonov approved these changes

2023-05-27 16:55 UTC, merged